name: Archive and Release

on:
  push:
    tags:
      - "v*" # Triggers workflow when a tag beginning with 'v' is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Create ZIP archive (excluding .gitkeep)
        run: |
          cd $GITHUB_WORKSPACE
          find . -name ".gitkeep" -type f -delete
          zip -r release.zip . -x "*.git*" "*.github/*"
          ls -lh release.zip

      - name: Generate Changelog
        id: changelog
        run: |
          # Gets commits between the last tag and the current tag
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 ${{ github.ref }}^)
          CHANGELOG=$(git log --pretty=format:"- %s (%h)" $PREVIOUS_TAG..${{ github.ref_name }})
          echo "changelog=$CHANGELOG" >> $GITHUB_OUTPUT


      - name: Create Release and Upload Asset
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }} # Tag name
          name: Release ${{ github.ref }} # Release title
          body: | # Release description
            ## Changelog :
            ${{ steps.changelog.outputs.changelog }}
          files: release.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
