name: Archive and Release

on:
  push:
    tags:
      - "v*" # Triggers workflow when a tag beginning with 'v' is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Create ZIP archive (excluding .gitkeep)
        run: |
          cd $GITHUB_WORKSPACE
          find . -name ".gitkeep" -type f -delete
          zip -r protonbus-vehicle-template_${{ github.ref_name }}.zip . -x "*.git*" "*.github/*" "*event.json*" "*bin/*"
          ls -lh protonbus-vehicle-template_${{ github.ref_name }}.zip

      - name: Read CHANGELOG.md
        id: changelog_file
        run: |
          if [ -f ".github/CHANGELOG.md" ]; then
            CHANGELOG_CONTENT=$(cat .github/CHANGELOG.md)
          else
            CHANGELOG_CONTENT=""
          fi
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Generate Changelog
        id: changelog
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 ${{ github.ref_name }}^ 2>/dev/null || git rev-list --max-parents=0 HEAD)
          CHANGELOG=$(git log --pretty=format:"- %s (%h)" "$PREVIOUS_TAG".."${{ github.ref_name }}")
          if [ -z "$CHANGELOG" ]; then
            CHANGELOG="No changes recorded since last tag."
          fi
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release and Upload Asset
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }} # Tag name
          name: Release ${{ github.ref_name }} # Release title
          body: | # Release description
            ${{ steps.changelog_file.outputs.content }}

            ## Changelog
            ${{ steps.changelog.outputs.changelog }}
          files: release.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
